runtime: nodejs18

service: wa-bot

env: standard
instance_class: F2


entrypoint: node index.js

env_variables:
  NODE_ENV: 'production'
  
handlers:
  - url: /public
    static_dir: dist/public
  
  - url: /views/(.*)
    static_files: dist/views/\1
    upload: dist/views/(.*)
  
  - url: /.*
    script: auto